import { ChangeEvent, FormEvent, useState } from "react";
import Campaign from "../Models/CampaignModel";
import Character from "../Models/CharacterModel";
import CampaignService from "../Services/campaignService";
import HeroService from "../Services/heroService";
import ImmersiveSelect from "./ImmersiveSelect";
import ModalShell from "./ModalShell";
import PlayerStepper from "./PlayerStepper";

type Props = { item: { type: "character"; value: Character } | { type: "campaign"; value: Campaign }; onClose: () => void; onSaved: (value: Character | Campaign) => void };
interface EditForm { name: string; description: string; visibility: "public" | "private" | "unlisted"; powers: string; weakness: string; shortDescription: string; system: string; tone: string; status: Campaign["status"]; min: number; max: number; schedule: string }
const EditCreationModal = ({ item, onClose, onSaved }: Props) => {
  const value = item.value;
  const [form, setForm] = useState<EditForm>(() => item.type === "character" ? { name: item.value.name, description: item.value.description, powers: item.value.details.powers, weakness: item.value.details.weakness, visibility: item.value.visibility, shortDescription: "", system: "", tone: "", status: "planning", min: 1, max: 1, schedule: "" } : { name: item.value.name, shortDescription: item.value.shortDescription, description: item.value.description, system: item.value.system, tone: item.value.tone, status: item.value.status, visibility: item.value.visibility, min: item.value.playerCount.min, max: item.value.playerCount.max, schedule: item.value.schedule, powers: "", weakness: "" });
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const change = (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setForm({ ...form, [event.target.name]: event.target.value });
  const setField = (name: string, fieldValue: string | number) => setForm({ ...form, [name]: fieldValue });
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { if (item.type === "character") { const data = form as { name: string; description: string; powers: string; weakness: string; visibility: "public" | "private" }; const response = await HeroService.update(value.id, { name: data.name, description: data.description, details: { powers: data.powers, weakness: data.weakness }, visibility: data.visibility }); onSaved(response.data.data); } else { const campaign = value as Campaign; const data = form as { name: string; shortDescription: string; description: string; system: string; tone: string; status: Campaign["status"]; visibility: Campaign["visibility"]; min: number; max: number; schedule: string }; const response = await CampaignService.update(campaign.id, { name: data.name, shortDescription: data.shortDescription, description: data.description, system: data.system, genres: campaign.genres, tone: data.tone, status: data.status, visibility: data.visibility, playerCount: { min: data.min, max: data.max }, schedule: data.schedule, contentWarnings: campaign.contentWarnings, map: { provider: "seed-preview", seed: campaign.map.seed, generatorVersion: campaign.map.generatorVersion, parameters: campaign.map.parameters } }); onSaved(response.data.data); } onClose(); } catch { setError("No se pudieron guardar los cambios."); } finally { setSaving(false); } };
  return <ModalShell onClose={onClose} label={`Editar ${value.name}`} wide><form className="edit-creation" onSubmit={submit}><span className="eyebrow">Editar {item.type === "character" ? "personaje" : "campaña"}</span><h2>{value.name}</h2><label>Nombre<input name="name" value={form.name} onChange={change} required /></label>{item.type === "character" ? <><label>Historia<textarea name="description" value={form.description} onChange={change} rows={5} required /></label><div className="field-pair"><label>Don<textarea name="powers" value={form.powers} onChange={change} rows={4} required /></label><label>Grieta<textarea name="weakness" value={form.weakness} onChange={change} rows={4} required /></label></div><label>Visibilidad<ImmersiveSelect name="visibility" value={form.visibility} onChange={setField} options={[{ value: "public", label: "Público" }, { value: "private", label: "Privado" }]} /></label></> : <><label>Resumen<input name="shortDescription" value={form.shortDescription} onChange={change} required /></label><label>Descripción<textarea name="description" value={form.description} onChange={change} rows={6} required /></label><div className="field-pair"><label>Sistema<input name="system" value={form.system} onChange={change} required /></label><label>Tono<input name="tone" value={form.tone} onChange={change} required /></label></div><div className="field-pair"><PlayerStepper label="Compañía mínima" value={form.min} onChange={(number) => setField("min", number)} /><PlayerStepper label="Compañía máxima" value={form.max} onChange={(number) => setField("max", number)} /></div><label>Estado<ImmersiveSelect name="status" value={form.status} onChange={setField} options={[{ value: "planning", label: "En preparación" }, { value: "active", label: "En curso" }, { value: "paused", label: "En pausa" }, { value: "completed", label: "Finalizada" }]} /></label><label>Visibilidad<ImmersiveSelect name="visibility" value={form.visibility} onChange={setField} options={[{ value: "public", label: "Pública" }, { value: "unlisted", label: "No listada" }, { value: "private", label: "Privada" }]} /></label></>}{error && <p className="form-error">{error}</p>}<footer><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={saving}>{saving ? "Guardando…" : "Guardar cambios"}</button></footer></form></ModalShell>;
};
export default EditCreationModal;
